# Generated by Django 4.2.14 on 2024-08-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0007_car_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="amount",
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="цена"
            ),
        ),
        migrations.AddField(
            model_name="moto",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="цена"
            ),
        ),
    ]
